language: php
php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - 7

env:
  global:
    - MYSQLPASSWD=''

before_script:
  - mysql < dbTables.sql -uroot

services:
  - mysql

install:
  - composer install

script: phpunit --testsuite travis_tests
